# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: github scraper unit test

on:
  push:
    paths:
      - .github/workflows/github-scraper-unit-test.yaml
      - scraper/github/**
    branches:
      - main
  pull_request:
    paths:
      - .github/workflows/github-scraper-unit-test.yaml
      - scraper/github/**
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: scraper/github/

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install virtualenv
          make install-deps

      - name: Lint with flake8
        run: |
          make lint

      - name: Test with pytest
        run: |
          make test
