# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: meilisearch index generator unit test

on:
  push:
    paths:
      - .github/workflows/meilisearch-index-generator-unit-test.yaml
      - tools/meilisearch-index-generator/**
    branches:
      - main
      - add-meilisearch-index-generator-deploy-action
  pull_request:
    paths:
      - .github/workflows/meilisearch-index-generator-unit-test.yaml
      - tools/meilisearch-index-generator/**
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: scraper/twitter/

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install virtualenv
          make install-deps

      - name: Lint with flake8
        run: |
          make lint

#       - name: Test with pytest
#         run: |
#           make test
