# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: twitter scraper unit test

on:
  push:
    paths:
      - .github/workflows/twitter-scraper-unit-test.yaml
      - scraper/twitter/**
    branches:
      - main
      - dev
  pull_request:
    paths:
      - .github/workflows/twitter-scraper-unit-test.yaml
      - scraper/twitter/**
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: scraper/twitter/

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
            
      - name: Lint with flake8
        run: | 
          python -m pip install --upgrade pip
          pip install flake8 
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 ./ --statistics
      
      - name: Install dependencies
        run: |
          pip install virtualenv
          pip install pytest
          virtualenv -p python3 venv
          source venv/bin/activate
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Test with pytest
        run: |
          source venv/bin/activate
          pytest

